edition = "2023";

package dolina.projects.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/projects/v1;projects_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = IMPLICIT;

import "google/protobuf/go_features.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

import "common/v1/pagination.proto";
import "projects/v1/project.proto";
import "common/v1/sort.proto";
import "common/v1/uuid.proto";

service ProjectService {
  rpc GetProjectByID(common.v1.ID) returns (Project) {
    option (google.api.http) = {
      get: "/api/v1/projects/{id}"
    };
  };

  rpc GetProjectByQueryFilter(ProjectsQueryFilter) returns (ProjectsQueryResponse) {
    option (google.api.http) = {
      get: "/api/v1/projects"
    };
  };

  rpc CreateProject(Project) returns (common.v1.ID) {
    option (google.api.http) = {
      put: "/api/v1/project",
      body: "*"
    };
  }

  rpc DeleteProjectByID(common.v1.ID) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/projects/{id}"
    };
  };
}

message ProjectsQueryFilter {
  string name = 1;

  repeated string label_list = 2;

  common.v1.Pagination pagination = 3;
  common.v1.Sort sort = 4;
}

message ProjectsQueryResponse {
  repeated Project projects_list = 1;

  common.v1.PaginationMetadata pagination = 2;
}