edition = "2023";

package dolina.projects.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/projects/v1;projects_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = EXPLICIT;

import "google/protobuf/go_features.proto";
import "google/protobuf/timestamp.proto";

message Revision {
  uint64 id = 1;

  string name = 2 [features.field_presence = EXPLICIT];
  repeated string tag_list = 3;

  uint64 project_id = 4;
  string project_slug = 5; // used to create new projects

  repeated string git_tags = 6;
  repeated string git_branches = 7;
  string git_commit_hash = 8 [features.field_presence = EXPLICIT];

  string vcs_url = 9 [features.field_presence = EXPLICIT];
  string created_by = 10 [features.field_presence = EXPLICIT];

  string sbom_file_uuid = 11 [features.field_presence = EXPLICIT];

  google.protobuf.Timestamp created_at = 12 [features.field_presence = EXPLICIT];
  google.protobuf.Timestamp updated_at = 13 [features.field_presence = EXPLICIT];
}

