edition = "2023";

package dolina.workers.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/workers/v1;workers_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = EXPLICIT;

import "google/protobuf/go_features.proto";

import "workers/v1/worker.proto";

// worker --> control center

service WorkerControlService {
  rpc Register(WorkerRegistration) returns (WorkerIdentity);

  rpc Heartbeat(stream WorkerStatus) returns (stream WorkerSignal);
}

