edition = "2023";

package dolina.filestore.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/filestore/v1;filestore_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = IMPLICIT;

import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/go_features.proto";
import "google/protobuf/timestamp.proto";

message FileKey {
  string key = 1;
}

message File {
  string file_name = 1;

  bytes content = 2 [features.field_presence = EXPLICIT];
  FileMetadata metadata = 3 [features.field_presence = EXPLICIT];
}

message FileUpload {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      title: "File upload"
      description: ""
    }
  };

  string file_name = 1;

  // base64 encoded file contents
  bytes content = 2 [features.field_presence = EXPLICIT];
  map<string, string> tag_map = 3;

  // when use_versioning is set to true file is saved with original name, without unique suffix this option will override existing file and increment its version
  bool use_versioning = 4;
}

message FileMetadata {
  string version = 1;
  uint64 total_size = 2;

  string content_type = 3;

  map<string, string> tag_map = 4;

  google.protobuf.Timestamp updated_at = 6;
  google.protobuf.Timestamp expired_at = 7 [features.field_presence = EXPLICIT];
}

message UploadStatus {
  string file_key = 1;
  uint64 received_size = 2;
}