edition = "2023";

package dolina.filestore.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/filestore/v1;filestore_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = IMPLICIT;

import "google/protobuf/go_features.proto";
import "google/protobuf/timestamp.proto";

message FileKey {
  string key = 1;
}

message FileChunk {
  bytes content = 1;
  FileMetadata metadata = 2 [features.field_presence = EXPLICIT];
}

message FileMetadata {
  string version = 1;
  uint64 total_size = 2;

  string content_type = 3;

  map<string, string> tag_map = 4;

  google.protobuf.Timestamp updated_at = 6;
  google.protobuf.Timestamp expired_at = 7 [features.field_presence = EXPLICIT];
}

message UploadStatus {
  string file_key = 1;
  uint64 received_size = 2;
}