edition = "2023";

package dolina.filestore.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/filestore/v1;filestore_v1";
option features.(pb.go).api_level = API_OPAQUE;

import "google/protobuf/go_features.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

import "filestore/v1/file.proto";
import "common/v1/uuid.proto";

service FilestoreService {
  rpc GetFileMetadataByKey(FileKey) returns (FileMetadata) {
    option (google.api.http) = {
      get: "/api/v1/filestore/{key}/metadata"
    };
  }

  rpc GetFileByKey(FileKey) returns (FileChunk) {
    option (google.api.http) = {
      get: "/api/v1/filestore/{key}"
    };
  }

  rpc DeleteFileByKey(FileKey) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/filestore/{key}"
    };
  }

  rpc GetFileStreamByUUID(common.v1.UUID) returns (stream FileChunk);

  rpc UploadFile(FileChunk) returns (UploadStatus) {
    option (google.api.http) = {
      post: "/api/v1/upload"
      body: "*",
    };
  }

  rpc UploadFileStream(stream FileChunk) returns (UploadStatus) {
    option (google.api.http) = {
      post: "/api/v1/upload/stream"
      body: "*",
    };
  }
}