edition = "2023";

package dolina.analysis.v1;

option go_package = "gitlab.domsnail.ru/dolina/dolina-aspm-api/api/gen/go/analysis/v1;analysis_v1";
option features.(pb.go).api_level = API_OPAQUE;
option features.field_presence = EXPLICIT;

import "google/protobuf/go_features.proto";
import "google/api/annotations.proto";

import "analysis/v1/analysis.proto";
import "analysis/v1/window.proto";
import "common/v1/uuid.proto";

service AnalysisService {
  // Synchronised method for reports analysis
  rpc AnalyzeReportsStream(AnalyzeOptions) returns (stream AnalysisWindow) {}

  // Asynchronous method for reports analysis, always returns uncertain info
  rpc AnalyzeReports(AnalyzeOptions) returns (AnalysisWindow) {
    option (google.api.http) = {
      post: "/api/v1/reports/analyze"
      body: "*"
    };
  }

  rpc GetAnalysisWindowByUUID(common.v1.UUID) returns (AnalysisWindow) {
    option (google.api.http) = {
      get: "/api/v1/analysis/windows/{uuid}"
    };
  }
}